setReset:
  location: "environments/env.a"
  description: "This is a button and a lightbulb! Note that the button stays depressed once it is touched (unless it is reset)"
  reset: "http://env.a:5001/resetall"
  infos:
    - "http://env.a:5001/checklight"
  actions:
    - "http://env.a:5001/pushbutton"
    - "http://env.a:5001/resetbutton"

2Toggle:
  location: "environments/env.b"
  description: "This is a button and a lightbulb! The light toggles every two presses."
  reset: "http://env.b:5001/resetall"
  infos:
    - "http://env.b:5001/checklight"
  actions:
    - "http://env.b:5001/pushbutton"

4Toggle:
  location: "environments/env.c"
  description: "This is a button and a lightbulb! The light toggles every four presses."
  reset: "http://env.c:5001/resetall"
  infos:
    - "http://env.c:5001/checklight"
  actions:
    - "http://env.c:5001/pushbutton"

2ToggleReset:
  location: "environments/env.d"
  description: "This is a button and a lightbulb! The light turns on after two presses. Turns off when reset is pressed."
  reset: "http://env.d:5001/resetall"
  infos:
    - "http://env.d:5001/checklight"
  actions:
    - "http://env.d:5001/pushbutton"
    - "http://env.d:5001/resetbutton"

2Toggle4Toggle:
  location: "environments/env.e"
  description: "This is 2 buttons and 2 lightbulbs! One light toggles every two presses. The other light toggles every four presses."
  reset: "http://env.e:5002/resetall"
  infos:
    - "http://env.e:5002/checklight1"
    - "http://env.e:5002/checklight2"
  actions:
    - "http://env.e:5002/pushbutton1"
    - "http://env.e:5002/pushbutton2"

2_4Toggle:
  location: "environments/env.f"
  description: "This is a buttons and 2 lightbulbs! One light toggles every two presses. The other light toggles every four presses."
  reset: "http://env.f:5002/resetall"
  infos:
    - "http://env.f:5002/checklight1"
    - "http://env.f:5002/checklight2"
  actions:
    - "http://env.f:5002/pushbutton1"

2Temp:
  location: "environments/env.g"
  description: "This is a button and a lightbulb! The light turns on temporarily every two presses."
  reset: "http://env.g:5002/resetall"
  infos:
    - "http://env.g:5002/checklight"
  actions:
    - "http://env.g:5002/pushbutton"

2Temp4Temp:
  location: "environments/env.h"
  description: "This is 2 buttons and 2 lightbulbs! The light turns on temporarily every two presses. The other light turns on temporarily every four presses."
  reset: "http://env.h:5002/resetall"
  infos:
    - "http://env.h:5002/checklight1"
    - "http://env.h:5002/checklight2"
  actions:
    - "http://env.h:5002/pushbutton2"
    - "http://env.h:5002/pushbutton1"
